= Releases

This document contains some information about the CI build, release notes and deployment.
Other infos are present in the top link:../../README.md[README].



== CI Build

.Build Server
|===
|server |master |develop |configuration

|https://travis-ci.org/oboehm/ClazzFish/[Travis-CI.org]
|https://travis-ci.org/oboehm/ClazzFish/branches[image:https://travis-ci.org/oboehm/ClazzFish.svg?branch=master[Build Status]]
|https://travis-ci.org/oboehm/ClazzFish/branches[image:https://travis-ci.org/oboehm/ClazzFish.svg?branch=develop[Build Status]]
|s. link:../.travis.yml[.travis.yml]

|https://sonarcloud.io/projects[sonarcloud.io]
|https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish[image:https://sonarcloud.io/api/project_badges/measure?metric=alert_status&project=de.aosd.clazzfish:clazzfish[Q-Gate]]
|https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish%3Adevelop[image:https://sonarcloud.io/api/project_badges/measure?metric=alert_status&project=de.aosd.clazzfish:clazzfish:develop[Q-Gate]]
|`sonar:sonar`

|
|https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish[image:https://sonarcloud.io/api/project_badges/measure?project=de.aosd.clazzfish%3Aclazzfish&metric=coverage[Coverage]]
|https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish%3Adevelop[image:https://sonarcloud.io/api/project_badges/measure?project=de.aosd.clazzfish%3Aclazzfish%3Adevelop&metric=coverage[Coverage]]
|

|
|https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish[image:https://sonarcloud.io/api/project_badges/measure?project=de.aosd.clazzfish%3Aclazzfish&metric=sqale_rating[Maintenance]]
 https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish[image:https://sonarcloud.io/api/project_badges/measure?project=de.aosd.clazzfish%3Aclazzfish&metric=reliability_rating[Reliability]]
 https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish[image:https://sonarcloud.io/api/project_badges/measure?project=de.aosd.clazzfish%3Aclazzfish&metric=security_rating[Security]]
|https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish%3Adevelop[image:https://sonarcloud.io/api/project_badges/measure?project=de.aosd.clazzfish%3Aclazzfish%3Adevelop&metric=sqale_rating[Maintenance]]
 https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish%3Adevelop[image:https://sonarcloud.io/api/project_badges/measure?project=de.aosd.clazzfish%3Aclazzfish%3Adevelop&metric=reliability_rating[Reliability]]
 https://sonarcloud.io/dashboard?id=de.aosd.clazzfish%3Aclazzfish%3Adevelop[image:https://sonarcloud.io/api/project_badges/measure?project=de.aosd.clazzfish%3Aclazzfish%3Adevelop&metric=security_rating[Security]]
|

|===

The CI build is started automatically after a commit and push to GitHub.



== Release Notes

=== 1.0 (SNAPSHOT)

* How to activate SQL logging?
  The answer to this question you can find now in the link:SQL-Logging.adoc[documentation].
  Also clazzfish-sample is added as new module which provides some example and ideas how to use ClazzFish.
* _fixed_: too many classes found by ClasspathMonitor.getConcreteClassList()
  (https://github.com/oboehm/ClazzFish/issues/1[issue #1])


=== 0.9 (01-Jan-2019)

* clazzfish-jdbc is added as new module to support JDBC monitoring.
  It provides a ProxyDriver as JDBC driver which allows you to log and monitor the SQL statements.
  I.e. you can ask the monitor how often an SQL statement is called and how long does it takes.


==== 0.8 (07-Nov-2018)

* Java agent for IBM classloader provided (clazzfish-agent)


=== 0.5 (10-Mar-2018)

* The first version contains mainly a ClasspathMonitor and ResourcepathMonitor as JMX bean.
  Originally these classes were part of the http://patterntesting.org[PatternTesting] project.
  With https://issues.sonatype.org/browse/OSSRH-38331[OSSRH-38331] ClassFish is sync'd with Central Maven.




== Deployment

This is a little checklist for the next release:

.Ordered
. create a release branch and change to it
. remove -SNAPSHOT in pom.xml (`mvn versions:set` followd by `mvn versions:commit`)
. build all artifacts:
  `mvn -B clean install source:jar javadoc:jar gpg:sign -Dgpg.passphrase=xx`
. use the script `src/script/deploy.sh` to upload bundles to https://oss.sonatype.org/
  (but don't forget to update the VERSION variable inside this script).
. after upload to the staging repository https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-8.ReleaseIt[release it]:
  select "Staging Repositories" on oss.sonatype.org, press "Refresh" and then "Close" and "Release".
. build the Javadoc (`mvn javadoc:aggregate`) and transfer `target/site/apidocs` to http://aosd.de/ClazzFish/
. checkin the pom.xml (if not already done), label the sources, e.g. with "clazzfish-0.9" and push it (`git push --tags`)
. merge the release branch to master and develop branch
. change to develop branch and start next SNAPSHOT
. after a few days: check ClazzFish with http://search.maven.org/#search%7Cga%7C1%7Cclazzfish[search.maven.org]
